<a href="https://colab.research.google.com/github/AleksandraOD/classification-apmath-21/blob/main/Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [4]:
## your code

a = np.arange(1, 21)
res = np.power(2, a) / a
res

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [5]:
## your code
a = np.arange(6)
array1 = np.power(0.1, 3 * a) 
array2= np.power(0.2, 4 * a)
res = np.dot(array1, array2)
res

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [6]:
## your code
m = np.zeros((8, 8), dtype=int)
m[1::2, ::2] = 1
m[::2, 1::2] = 1
m

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [8]:
X = np.random.random((5, 2))

## your code
print('Декартова СК\n', X)
X[:, 0] = np.sqrt(np.power(X[:, 0], 2) + np.power(X[:, 1], 2))
X[:, 1] = np.arctan2(X[:, 1], X[:, 0])
print('Полярная СК\n', X)

Декартова СК
 [[0.46890804 0.42831624]
 [0.53935268 0.04682028]
 [0.63340817 0.58107258]
 [0.62035862 0.6158108 ]
 [0.97297382 0.92240463]]
Полярная СК
 [[0.63508231 0.59335546]
 [0.54138106 0.08626839]
 [0.85956457 0.59444187]
 [0.87410969 0.61374012]
 [1.34071188 0.60262418]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [11]:
X = np.random.random((10, 10))

## your code
X = np.random.random((10, 10))
print(X)
ind = np.argmax(X)
print('\nзначение: ', X.flat[ind], '\nиндексы: ', (ind // 10, ind % 10))

[[0.1157204  0.46608767 0.69835272 0.21798691 0.10062726 0.35759467
  0.01228186 0.80047255 0.73071108 0.32622547]
 [0.90427615 0.44961117 0.19072115 0.68991799 0.62320305 0.91987484
  0.99587213 0.39155409 0.30826681 0.01289833]
 [0.44712882 0.41056335 0.82138975 0.52854877 0.77017323 0.86115391
  0.39173326 0.47267907 0.49245152 0.37760963]
 [0.89988984 0.40251887 0.04424185 0.42269936 0.30143675 0.89643331
  0.53592371 0.41608667 0.2914079  0.80110727]
 [0.27361939 0.34110907 0.76045366 0.71927332 0.4736984  0.17395303
  0.67972296 0.03896416 0.0590775  0.83172705]
 [0.18621322 0.19807467 0.32641079 0.70091824 0.3734781  0.73930202
  0.62178888 0.99146632 0.15718804 0.47654438]
 [0.37884343 0.02768606 0.82636783 0.60358269 0.98099272 0.73137405
  0.05715727 0.67203759 0.38078751 0.11538701]
 [0.66039137 0.9390728  0.02256834 0.20776528 0.24590263 0.66716324
  0.25178332 0.53889634 0.62114656 0.44005915]
 [0.94023348 0.86781001 0.85467581 0.44806149 0.77522242 0.45368105
  0.59157628

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [14]:
X = np.random.random((10, 2))
print('X:\n', X)
y = np.random.random((1, 2))
print('\ny:\n', y)

## your code
dist = np.sqrt(
    np.power((X[:, 0] - y[0, 0]), 2) + np.power((X[:, 1] - y[0, 1]), 2))
print('\n расстояния:\n', dist)
print('\n ближайщая точка:\n', X[np.argmin(dist)])

X:
 [[0.48367115 0.65755758]
 [0.38234748 0.58487232]
 [0.35557447 0.14211077]
 [0.29621754 0.29088004]
 [0.1304617  0.33712795]
 [0.05448951 0.4738464 ]
 [0.70304034 0.08688631]
 [0.02965514 0.77305178]
 [0.64829825 0.80829781]
 [0.94927784 0.61446569]]

y:
 [[0.41208368 0.57328146]]

 расстояния:
 [0.1105768  0.03191535 0.43485798 0.30524667 0.36753153 0.37116159
 0.56677688 0.43146237 0.33321165 0.53877055]

 ближайщая точка:
 [0.38234748 0.58487232]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [15]:
## your code
@np.vectorize
def func(x):
    if x<0:
        return x**2 + 2 * x + 6
    elif x>=2:
        return x**2 + 4 * x - 4
    else:
        return x+6

x = np.linspace(-3, 3, 100)
func(x)

array([ 9.        ,  8.76124885,  8.52984389,  8.30578512,  8.08907254,
        7.87970615,  7.67768595,  7.48301194,  7.29568411,  7.11570248,
        6.94306703,  6.77777778,  6.61983471,  6.46923783,  6.32598714,
        6.19008264,  6.06152433,  5.94031221,  5.82644628,  5.71992654,
        5.62075298,  5.52892562,  5.44444444,  5.36730946,  5.29752066,
        5.23507805,  5.17998163,  5.1322314 ,  5.09182736,  5.05876951,
        5.03305785,  5.01469238,  5.00367309,  5.        ,  5.00367309,
        5.01469238,  5.03305785,  5.05876951,  5.09182736,  5.1322314 ,
        5.17998163,  5.23507805,  5.29752066,  5.36730946,  5.44444444,
        5.52892562,  5.62075298,  5.71992654,  5.82644628,  5.94031221,
        6.03030303,  6.09090909,  6.15151515,  6.21212121,  6.27272727,
        6.33333333,  6.39393939,  6.45454545,  6.51515152,  6.57575758,
        6.63636364,  6.6969697 ,  6.75757576,  6.81818182,  6.87878788,
        6.93939394,  7.        ,  7.06060606,  7.12121212,  7.18

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [16]:
X = np.random.random((10, 10))

## your code
X = X - X.mean(axis=0)
print('Check result:\n', X.mean(axis=0))

Check result:
 [ 5.55111512e-17  2.22044605e-17  3.33066907e-17  3.88578059e-17
 -4.44089210e-17  2.22044605e-17  5.55111512e-18  5.55111512e-17
  6.10622664e-17 -3.33066907e-17]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [18]:
X = np.random.normal(loc=5, scale=2., size=1000)
print('выборочное среднее: ', np.mean(X), '\nдисперсия: ', np.nanvar(X))

выборочное среднее:  5.0231729356088985 
дисперсия:  4.084372939869875


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [19]:
## your code
np.indices((5, 5)).sum(axis = 0) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [29]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[3, 0, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [30]:
## your code
def opt_sample(x, c):
    assert len(x) > 0

    indx = np.arange(0, len(x))
    prob = x / np.sum(x)
    return np.random.choice(indx, size=c, p=prob)

opt_sample([50, 3, 1, 7, 20], 5)

array([3, 0, 0, 0, 0])